/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 bleu.gltf --transform 
Files: bleu.gltf [275.06KB] > bleu-transformed.glb [475.5KB] (-73%)
Author: szsakaria (https://sketchfab.com/szsakaria)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bleu-de-chanel-perfume-34150421c7154997bd0060f3f66c1c4f
Title: BLEU DE CHANEL Perfume.
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bleu-transformed.glb')
  return (
    <group {...props} dispose={null} scale={[0.1, 0.1, 0.1]}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.PaletteMaterial002}
        position={[0, 3.378, 0]}
      />
    </group>
  );
}

useGLTF.preload('/bleu-transformed.glb')
