/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 books.gltf --transform 
Files: books.gltf [2.95MB] > books-transformed.glb [698.46KB] (76%)
Author: vikashmurmoo (https://sketchfab.com/vikashmurmoo)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/books-708f7cd774d549899daf1511aa9541bf
Title: Books
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/books-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Books_Odyssey} position={[0, 0.234, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Books_Audio} position={[0.3, 0.127, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Books_BlackBlue} position={[0.3, 0.011, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Books_Bristol} position={[0.3, 0.031, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Books_DorianGray} position={[0, 0.018, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Books_Dreaming} position={[0, 0.18, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Books_Enchanters} position={[0, 0.117, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.Books_Eragon} position={[0, 0.15, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.Books_Euro} position={[0.3, 0.106, 0]} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.Books_Everyone} position={[0.3, 0.05, 0]} scale={0.963} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Books_History} position={[0.3, 0.069, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Books_Mathematical} position={[0, 0.207, 0]} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.Books_Ramiel} position={[0.3, 0.088, 0]} scale={0.909} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.Books_Reef} position={[0.3, 0.147, 0]} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Books_Tomorrow} position={[0, 0.086, 0]} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.Books_TwentyFive} position={[0, 0.055, 0]} />
    </group>
  )
}

useGLTF.preload('/books-transformed.glb')
