/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 gift.gltf --transform 
Files: gift.gltf [1.89MB] > gift-transformed.glb [116.52KB] (94%)
Author: gorzi (https://sketchfab.com/gorzi90)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gift-f3d8abcd3b9442f39a9a2017d59b56a1
Title: Gift
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gift-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube000.geometry} material={materials.Material} position={[0.077, 1.548, -0.019]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube000_1.geometry} material={materials['Material.001']} position={[0.077, 1.548, -0.019]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/gift-transformed.glb')
