/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 question.gltf --transform 
Files: question.gltf [423.9KB] > question-transformed.glb [77.07KB] (82%)
Author: Miguelangelo Rosario (https://sketchfab.com/miguelangelo2k)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/question-mark-d812fdd4efd84f77af7883a3a30b4d5b
Title: Question Mark
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/question-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" position={[0, -50.538, -83.344]}>
          <group name="questionmark" position={[5.011, 0.221, 71.971]}>
            <mesh name="questionmark_03_-_Default_0" geometry={nodes['questionmark_03_-_Default_0'].geometry} material={materials['03_-_Default']} />
            <mesh name="questionmark_05_-_Default_0" geometry={nodes['questionmark_05_-_Default_0'].geometry} material={materials['05_-_Default']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/question-transformed.glb')
