/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 random_books.gltf --transform 
Files: random_books.gltf [5.18MB] > random_books-transformed.glb [886.53KB] (83%)
Author: isnainul (https://sketchfab.com/isnainul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/random-books-df5211e734f044229951a0c46c3f83ba
Title: Random Books
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/random_books-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Buku1_0.geometry} material={materials.BookPaper} position={[0, 0, 0.078]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku1_1.geometry} material={materials.BookCover1} position={[0, 0, 0.078]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku2_1.geometry} material={materials.BookCover2} position={[-0.031, 0, 0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku3_1.geometry} material={materials.BookCover3} position={[0.006, 0, -0.032]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku4_1.geometry} material={materials.BookCover4} position={[-0.015, 0, -0.803]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku5_1.geometry} material={materials.BookCover5} position={[-0.019, 0, -0.746]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku6_1.geometry} material={materials.BookCover6} position={[-0.011, 0, -0.687]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku7_1.geometry} material={materials.BookCover7} position={[-0.031, 0, -0.249]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.292} />
      <mesh geometry={nodes.Buku8_1.geometry} material={materials.BookCover8} position={[-0.01, 0, -0.282]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku9_1.geometry} material={materials.BookCover9} position={[-0.007, 0, -0.358]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku10_1.geometry} material={materials.BookCover10} position={[-0.015, 0, -0.32]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku11_1.geometry} material={materials.BookCover11} position={[0, 0, -0.623]} rotation={[-Math.PI / 2, 0, 0]} scale={0.292} />
      <mesh geometry={nodes.Buku12_1.geometry} material={materials.BookCover12} position={[-0.023, 0, 0.148]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.292, 0.425, 0.292]} />
    </group>
  )
}

useGLTF.preload('/random_books-transformed.glb')
