/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 series.gltf --transform 
Files: series.gltf [3.61MB] > series-transformed.glb [1.76MB] (51%)
Author: yanix (https://sketchfab.com/yanix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flowers-b56e199f962f49b29686c1a891fe47bd
Title: Flowers
*/

import  { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default  function Model(props) {
  const { nodes, materials } = useGLTF('/series-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder005_0.geometry} material={materials.lower_magnetta} position={[0.003, 0.096, 0.04]} rotation={[-2.091, 0.591, -1.819]} scale={[0.17, 0.17, 0.212]} />
      <mesh geometry={nodes.Cylinder004_0.geometry} material={materials.lower_red} position={[0.064, 0.075, 0.008]} rotation={[-1.41, -0.274, 1.345]} scale={[0.173, 0.173, 0.215]} />
      <instancedMesh args={[nodes.Cylinder011_0.geometry, materials.flower_yellow, 6]} instanceMatrix={nodes.Cylinder011_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/series-transformed.glb')
